package com.twu.biblioteca.EnumTypes;

public enum ActionType {
	GOTO_LIST_BOOKS, 
	GOTO_RETURN_BOOKS, 
	QUIT, 
	INVALID_MENU_CHOICE,
	BACK_TO_MAIN_MENU, 
	CHECKOUT_BOOK,
	INVALID_LIST_BOOK_MENU_CHOICE,
	RETURN_BOOK,
	INVALID_RETURN_BOOK_MENU_CHOICE,
	UNRECOGNISED_ACTION,
	GOTO_LIST_MOVIES,
	CHECKOUT_MOVIE,
	INVALID_LIST_MOVIE_MENU_CHOICE
}
