package com.twu.biblioteca;

public enum ActionType {
	GOTO_LIST_BOOKS, 
	GOTO_RETURN_BOOKS, 
	QUIT, 
	INVALID_MENU_CHOICE,
	BACK_TO_MAIN_MENU, 
	CHECKOUT_BOOK,
	INVALID_LIST_BOOK_MENU_CHOICE,
	RETURN_BOOK,
	INVALID_RETURN_BOOK_MENU_CHOICE
}
